[package]
name = "nirvana"
version = "0.1.0"
edition = "2024"

[lib]
name = "nirvana"
path = "src/lib.rs"

[[bin]]
name = "nirvana"
path = "src/main.rs"

[workspace.dependencies]
bevy = { version = "0.19.0" }

[dependencies]
bevy.workspace = true

# Dev only: 'cargo run --features dev' turns on dynamic linking
[features]
dev = [
    "bevy/debug",
    "bevy/dynamic_linking",
    "bevy/file_watcher",     # shader hot-reload, dev only
    "bevy/bevy_dev_tools",
    # "dep:bevy-inspector-egui",
]

# light optimization, fast recompiles
[profile.dev]
opt-level = 1

# dependencies: full optimisation, compile once
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[profile.dist]
inherits = "release"
lto = "fast"
